/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RentContract } from "./RentContract";
export type { RentContractFactory } from "./RentContractFactory";
